import fs from 'fs-extra';
import path from 'path';
// ── Existing helpers ──────────────────────────────────────────────────────────
function topImports(imports, n = 10) {
    const counts = new Map();
    for (const imp of imports) {
        counts.set(imp.to, (counts.get(imp.to) ?? 0) + 1);
    }
    return [...counts.entries()]
        .sort((a, b) => b[1] - a[1])
        .slice(0, n)
        .map(([module, count]) => ({ module, count }));
}
export async function generateAnalysis(result, outputDir) {
    await fs.ensureDir(outputDir);
    const top = topImports(result.imports);
    const routeTable = result.routes.length > 0
        ? [
            '| Method | Path | File | Line |',
            '|--------|------|------|------|',
            ...result.routes.map(r => `| \`${r.method}\` | \`${r.path}\` | ${r.file} | ${r.line} |`)
        ].join('\n')
        : '_No Express or Next.js routes detected._';
    const importList = top.length > 0
        ? top.map((t, i) => `${i + 1}. \`${t.module}\` — imported **${t.count}** time${t.count === 1 ? '' : 's'}`).join('\n')
        : '_No imports detected._';
    const md = `# Project Architecture

_Generated by wmx analyze on ${new Date().toISOString()}_

## Folder Structure

\`\`\`
${result.folderTree}
\`\`\`

## API Routes

${routeTable}

## Top Imports

${importList}

## Exports Summary

Total exported symbols: **${result.exports.length}**

| Type | Count |
|------|-------|
| Functions | ${result.exports.filter(e => e.type === 'function').length} |
| Classes | ${result.exports.filter(e => e.type === 'class').length} |
| Constants | ${result.exports.filter(e => e.type === 'const').length} |
| Types | ${result.exports.filter(e => e.type === 'type').length} |
`;
    await fs.writeFile(path.join(outputDir, 'analysis.md'), md, 'utf8');
    await fs.writeFile(path.join(outputDir, 'analysis.json'), JSON.stringify(result, null, 2), 'utf8');
}
// ── Project structure tree helper (for generateReadme) ────────────────────────
const PROJ_IGNORE_DIRS = new Set(['node_modules', '.git', 'dist', '.wmx']);
const PROJ_IGNORE_FILES = new Set(['.env', '.env.example']);
async function buildProjectStructure(dir, maxDepth, depth = 0) {
    if (depth >= maxDepth)
        return '';
    let entries;
    try {
        entries = await fs.readdir(dir);
    }
    catch {
        return '';
    }
    const filtered = entries.filter(e => {
        if (PROJ_IGNORE_DIRS.has(e))
            return false;
        if (PROJ_IGNORE_FILES.has(e))
            return false;
        if (/\.lock$/.test(e))
            return false;
        return true;
    });
    filtered.sort();
    const indent = '  '.repeat(depth);
    const lines = [];
    for (const entry of filtered) {
        const fullPath = path.join(dir, entry);
        let isDir = false;
        try {
            const stat = await fs.stat(fullPath);
            isDir = stat.isDirectory();
        }
        catch {
            continue;
        }
        if (isDir) {
            lines.push(`${indent}${entry}/`);
            const sub = await buildProjectStructure(fullPath, maxDepth, depth + 1);
            if (sub)
                lines.push(sub);
        }
        else {
            lines.push(`${indent}${entry}`);
        }
    }
    return lines.join('\n');
}
// ── generateReadme ────────────────────────────────────────────────────────────
export async function generateReadme(cwd) {
    // Read package.json
    let pkg = {};
    try {
        const raw = await fs.readFile(path.join(cwd, 'package.json'), 'utf8');
        pkg = JSON.parse(raw);
    }
    catch { /* missing or invalid — use defaults */ }
    // Read .wmxrc.json
    let wmxrc = {};
    try {
        const raw = await fs.readFile(path.join(cwd, '.wmxrc.json'), 'utf8');
        wmxrc = JSON.parse(raw);
    }
    catch { /* missing — use defaults */ }
    // Read .env.example
    let envExampleRaw = '';
    try {
        envExampleRaw = await fs.readFile(path.join(cwd, '.env.example'), 'utf8');
    }
    catch { /* missing — handled below */ }
    // 1. Title
    const title = pkg.name ?? 'My Project';
    // 2. Description
    const description = pkg.description ?? 'A project built with wmx';
    // 3. Tech Stack
    const deps = pkg.dependencies ?? {};
    const devDeps = pkg.devDependencies ?? {};
    const allDeps = { ...deps, ...devDeps };
    const techMap = [
        ['react', 'React'],
        ['express', 'Express'],
        ['mongoose', 'MongoDB'],
        ['next', 'Next.js'],
        ['pg', 'PostgreSQL'],
        ['vue', 'Vue'],
    ];
    const detectedTech = techMap
        .filter(([key]) => key in allDeps)
        .map(([, label]) => `- ${label}`);
    const techStackSection = detectedTech.length > 0
        ? detectedTech.join('\n')
        : '_No tech stack detected._';
    // 4. Prerequisites
    const packageManager = wmxrc.packageManager;
    const prereqItems = ['- Node.js >= 18', ...(packageManager ? [`- ${packageManager}`] : [])];
    const prerequisitesSection = prereqItems.join('\n');
    // 5. Installation
    const repoObj = pkg.repository;
    const repoUrl = typeof repoObj === 'string'
        ? repoObj
        : (repoObj?.url ?? 'https://github.com/your-org/your-repo');
    const projectName = pkg.name ?? 'your-project';
    const installCmd = packageManager === 'pnpm' ? 'pnpm install'
        : packageManager === 'bun' ? 'bun install'
            : packageManager === 'yarn' ? 'yarn install'
                : 'npm install';
    // 6. Environment Variables
    const envKeys = envExampleRaw
        .split('\n')
        .filter(line => line.includes('=') && !line.trimStart().startsWith('#'))
        .map(line => line.split('=')[0].trim())
        .filter(Boolean);
    const envSection = envKeys.length > 0
        ? '```bash\n' + envKeys.map(k => `${k}=`).join('\n') + '\n```'
        : '_No environment variables required._';
    // 7. Available Scripts
    const scripts = pkg.scripts ?? {};
    const scriptEntries = Object.entries(scripts);
    const scriptsSection = scriptEntries.length > 0
        ? scriptEntries.map(([key, val]) => `- \`npm run ${key}\` — ${val}`).join('\n')
        : '_No scripts defined._';
    // 8. Project Structure (2 levels deep)
    const structure = await buildProjectStructure(cwd, 2);
    // 9. License
    const license = pkg.license ?? 'MIT';
    return `# ${title}

${description}

## Tech Stack

${techStackSection}

## Prerequisites

${prerequisitesSection}

## Installation

\`\`\`bash
1. git clone ${repoUrl}
2. cd ${projectName}
3. ${installCmd}
\`\`\`

## Environment Variables

${envSection}

## Available Scripts

${scriptsSection}

## Project Structure

\`\`\`
${structure}
\`\`\`

## License

This project is licensed under the ${license} license.
`;
}
// ── generateArchitectureDocs ──────────────────────────────────────────────────
export function generateArchitectureDocs(analysis) {
    // Derive a unique source-file count from the data available in AnalysisResult
    const uniqueFiles = new Set([
        ...analysis.imports.map(i => i.from),
        ...analysis.exports.map(e => e.file),
        ...analysis.routes.map(r => r.file),
    ]).size;
    // API Routes table
    const routeTable = analysis.routes.length > 0
        ? [
            '| Method | Endpoint | File | Description |',
            '|--------|----------|------|-------------|',
            ...analysis.routes.map(r => `| \`${r.method}\` | \`${r.path}\` | ${r.file} |  |`)
        ].join('\n')
        : '_No API routes detected._';
    // Key Dependencies — external (non-relative) import targets, deduped
    const externalDeps = [...new Set(analysis.imports
            .map(i => i.to)
            .filter(m => !m.startsWith('.') && !m.startsWith('/')))].sort();
    const depsSection = externalDeps.length > 0
        ? externalDeps.map(d => `- \`${d}\``).join('\n')
        : '_No external dependencies detected._';
    return `# Project Architecture

## Overview

This document describes the architecture of the project.

Analyzed **${uniqueFiles}** source files.

## Folder Structure

\`\`\`
${analysis.folderTree}
\`\`\`

## API Routes

${routeTable}

## Key Dependencies

${depsSection}
`;
}
// ── generateApiDocs ───────────────────────────────────────────────────────────
export function generateApiDocs(routes) {
    const routeTable = routes.length > 0
        ? [
            '| Method | Endpoint | File | Description |',
            '|--------|----------|------|-------------|',
            ...routes.map(r => `| \`${r.method}\` | \`${r.path}\` | ${r.file} |  |`)
        ].join('\n')
        : '_No routes detected._';
    return `# API Reference

${routeTable}

_Update the Description column with endpoint-specific documentation._
`;
}
