import fs from 'fs-extra'
import path from 'path'
import type { ProjectMemory } from 'wmx-os-scanners'

function routeTable(routes: ProjectMemory['routes']): string {
  if (routes.length === 0) return '_No routes detected._'
  return [
    '| Method | Path | File |',
    '|--------|------|------|',
    ...routes.map(r => `| \`${r.method}\` | \`${r.path}\` | ${r.file} |`),
  ].join('\n')
}

function apiTable(routes: ProjectMemory['apiRoutes']): string {
  if (routes.length === 0) return '_No API endpoints detected._'
  return [
    '| Method | Path | File | Line |',
    '|--------|------|------|------|',
    ...routes.map(r => `| \`${r.method}\` | \`${r.path}\` | ${r.file} | ${r.line} |`),
  ].join('\n')
}

function componentList(items: ProjectMemory['components']): string {
  if (items.length === 0) return '_None detected._'
  return items.map(c => `- \`${c.name}\` — ${c.file}`).join('\n')
}

export function generateMemoryDoc(memory: ProjectMemory): string {
  return `# Project Memory

_Generated by \`wmx memory\` on ${new Date().toISOString()}_

This file summarizes the project for AI assistants (Claude, ChatGPT, Cursor, etc.) so they can understand the codebase without re-scanning it from scratch.

## Project Summary

- **Name:** ${memory.projectName}
- **Description:** ${memory.description || '_No description in package.json_'}
- **Framework:** ${memory.framework ?? 'unknown'}
- **Database:** ${memory.database ?? 'none detected'}
- **Package manager:** ${memory.packageManager ?? 'unknown'}

## Architecture

- Framework: **${memory.framework ?? 'unknown'}**
- Database: **${memory.database ?? 'none detected'}**
- Total page routes: **${memory.routes.length}**
- Total API endpoints: **${memory.apiRoutes.length}**
- Total components: **${memory.components.length}**
- Total hooks: **${memory.hooks.length}**

## Routes

${routeTable(memory.routes)}

## API

${apiTable(memory.apiRoutes)}

## Database

${memory.database ? `This project uses **${memory.database}**.` : 'No database dependency detected.'}

## Hooks

${componentList(memory.hooks)}

## Components

${componentList(memory.components)}

## Coding Style

- Quotes: **${memory.codingStyle.quotes}**
- Semicolons: **${memory.codingStyle.semicolons ? 'yes' : 'no'}**
- Indentation: **${memory.codingStyle.indent}**

## Naming Convention

- Component files: **${memory.namingConvention.componentFiles}**
- General files: **${memory.namingConvention.generalFiles}**

## Folder Structure

\`\`\`
${memory.folderTree}
\`\`\`
`
}

export async function writeMemoryDoc(memory: ProjectMemory, outputDir: string): Promise<void> {
  await fs.ensureDir(outputDir)
  await fs.writeFile(path.join(outputDir, 'memory.md'), generateMemoryDoc(memory), 'utf8')
  await fs.writeFile(path.join(outputDir, 'memory.json'), JSON.stringify(memory, null, 2), 'utf8')
}
