export const TUI_COMMANDS = [
  {
    key: "init",
    label: "wmx init",
    description: "Scaffold a new full-stack project from a template.",
    options: ["--template <name>", "--yes (skip prompts)"],
    run: "init",
  },
  {
    key: "check",
    label: "wmx check",
    description: "Verify required tools and environment variables are present.",
    options: ["--json (output as JSON)"],
    run: "check",
  },
  {
    key: "doctor",
    label: "wmx doctor",
    description: "Run project health checks and report issues.",
    options: ["--fix (auto-fix issues)", "--json (output as JSON)"],
    run: "doctor",
  },
  {
    key: "stats",
    label: "wmx stats",
    description: "Count files, lines, components, and pages in the project.",
    options: ["--json (output as JSON)"],
    run: "stats",
  },
  {
    key: "analyze",
    label: "wmx analyze",
    description: "Detect routes, imports, and exports. Writes .wmx/analysis.md.",
    options: ["--json (output as JSON)"],
    run: "analyze",
  },
  {
    key: "docs",
    label: "wmx docs",
    description: "Generate README.md, ARCHITECTURE.md, and API.md.",
    options: ["--readme", "--arch", "--api", "--all", "--output <dir>", "--overwrite"],
    run: "docs --all",
  },
  {
    key: "deps",
    label: "wmx deps",
    description: "Scan for unused, missing, heavy, and outdated dependencies.",
    options: ["--unused", "--heavy", "--outdated", "--all", "--json"],
    run: "deps --all",
  },
  {
    key: "upgrade",
    label: "wmx upgrade",
    description: "Interactively upgrade outdated dependencies.",
    options: ["--dry-run (preview without changes)"],
    run: "upgrade",
  },
  {
    key: "deploy",
    label: "wmx deploy",
    description: "Generate deployment config for Vercel, Render, or Netlify.",
    options: ["--provider <vercel|render|netlify>", "--output <dir>"],
    run: "deploy",
  },
  {
    key: "snapshot",
    label: "wmx snapshot",
    description: "Save and restore project state snapshots.",
    options: ["save [name]", "list", "restore <name>"],
    run: "snapshot list",
  },
  {
    key: "env",
    label: "wmx env",
    description: "Manage .env keys: list, add, remove, and sync with .env.example.",
    options: ["list", "add <KEY> <VALUE>", "remove <KEY>", "sync"],
    run: "env list",
  },
  {
    key: "config",
    label: "⚙  Config",
    description: "Create or update your .wmxrc.json project config. Set framework, backend, database, package manager, and deploy provider.",
    options: ["set  Run interactive wizard (default)", "show  Display current config", "reset  Delete .wmxrc.json"],
    run: "config show",
  },
  {
    key: "info",
    label: "ℹ  Project Info",
    description: "Show project summary: framework, database, git branch, node version, and more.",
    options: ["--json  Output as JSON"],
    run: "info",
  },
  {
    key: "tree",
    label: "🌲 File Tree",
    description: "Visual directory tree of your project.",
    options: ["--depth <n>  Max depth (default: 3)", "--json  Output as JSON"],
    run: "tree",
  },
  {
    key: "route",
    label: "🛣  Route Scanner",
    description: "List all API routes (Express) and page routes (Next.js) in your project.",
    options: ["--filter <method>  Filter by HTTP method (GET, POST, etc.)", "--json  Output as JSON"],
    run: "route",
  },
  {
    key: "api",
    label: "⚡ API Inspector",
    description: "List all Express API endpoints grouped by file.",
    options: ["--method <method>  Filter by HTTP method", "--file <pattern>  Filter by file path", "--json  Output as JSON"],
    run: "api",
  },
  {
    key: "unused",
    label: "🗑  Unused Scanner",
    description: "Find unused asset files (images, SVGs, fonts) and unused exports in your project.",
    options: ["--files  Show only unused asset files", "--exports  Show only unused exports", "--json  Output as JSON"],
    run: "unused",
  },
  {
    key: "size",
    label: "📦 Size Report",
    description: "Show the largest JS, CSS, and image files in your project.",
    options: ["--top <n>  Results per section (default: 5)", "--json  Output as JSON"],
    run: "size",
  },
  {
    key: "publish",
    label: "wmx publish",
    description: "Bump version, update changelog, git tag, and publish to npm.",
    options: ["--dry-run", "--skip-build", "--skip-git"],
    run: "publish --dry-run",
  },
]
